import type { AlarmGroup, ReviewItem, ScrapItem } from './myPage.types';

export const MY_PAGE_SCRAPS: ScrapItem[] = [
  {
    name: '삼성전자',
    code: '005930',
    color: '#1428a0',
    ini: '삼',
    date: '2026.02.26',
    eventType: '기업·실적',
    chg: '+19.47%',
  },
  {
    name: '삼성전자',
    code: '005930',
    color: '#1428a0',
    ini: '삼',
    date: '2026.01.22',
    eventType: '시장 수요',
    chg: '+7.4%',
  },
  {
    name: 'SK하이닉스',
    code: '000660',
    color: '#EA1917',
    ini: 'SK',
    date: '2026.04.19',
    eventType: '기업·실적',
    chg: '-5.9%',
  },
  {
    name: '현대차',
    code: '005380',
    color: '#002c5f',
    ini: 'H',
    date: '2026.04.19',
    eventType: '기업·실적',
    chg: '-5.9%',
  },
];

export const MY_PAGE_REVIEW_DATA: ReviewItem[] = [
  {
    name: '삼성전자',
    code: '005930',
    color: '#1428a0',
    ini: '삼',
    prediction: '상승예측',
    result: '적중',
    chg: '+17.2%',
    date: '2026.03.15',
    bg: '#f0fdf4',
    resultColor: '#16a34a',
  },
  {
    name: 'SK하이닉스',
    code: '000660',
    color: '#EA1917',
    ini: 'SK',
    prediction: '하락예측',
    result: '미적중',
    chg: '+17.2%',
    date: '2026.03.15',
    bg: '#fff1f2',
    resultColor: '#dc2626',
  },
  {
    name: '현대차',
    code: '005380',
    color: '#002c5f',
    ini: 'H',
    prediction: '횡보예측',
    result: '미적중',
    chg: '-5.9%',
    date: '2026.03.15',
    bg: '#fff1f2',
    resultColor: '#dc2626',
  },
  {
    name: '삼성전자',
    code: '005930',
    color: '#1428a0',
    ini: '삼',
    prediction: '상승예측',
    result: '적중',
    chg: '+7.4%',
    date: '2026.03.12',
    bg: '#f0fdf4',
    resultColor: '#16a34a',
  },
];

export const MY_PAGE_ALARM_HISTORY: AlarmGroup[] = [
  {
    ini: '삼',
    color: '#1428a0',
    name: '삼성전자',
    code: '005930',
    badge: 3,
    badgeColor: '#dc2626',
    relativeTime: '3일 전',
    summaryLine: '시장 수요, 투자 외 2건',
    items: [
      {
        dotColor: '#3b82f6',
        headline: 'HBM3E 납품 재개 기대감',
        chg: '+19.47%',
        desc: 'HBM3E 납품 재개 기대감으로 외국인 매수세가 집중되며 고가 228,500원을 기록했습니다.',
        tags: [
          { label: '#HBM', variant: 'solid', tone: 'neutral' },
          { label: '#외국인 매수', variant: 'solid', tone: 'neutral' },
        ],
      },
      {
        dotColor: '#f97316',
        headline: '📌 스크랩 이벤트 1개월 복기',
        chg: null,
        desc: '+6.61% 이벤트를 스크랩한 지 1개월이 됐어요. 당시 예측이 맞았는지 확인해보세요.',
        tags: [{ label: '#스크랩 복기', variant: 'solid', tone: 'neutral' }],
      },
    ],
    date: '2026.03.15',
    isToday: true,
  },
  {
    ini: 'SK',
    color: '#EA1917',
    name: 'SK하이닉스',
    code: '000660',
    badge: 2,
    badgeColor: '#2563eb',
    relativeTime: '1일 전',
    summaryLine: '급락 · 실적 이슈',
    items: [
      {
        dotColor: '#2563eb',
        headline: '실적 우려·납품 지연 이슈',
        chg: '-8.23%',
        desc: '실적 우려 및 납품 지연 이슈로 매도 우위가 이어졌습니다.',
        tags: [{ label: '기업·실적', variant: 'solid', tone: 'neutral' }],
      },
    ],
    date: '2026.03.15',
    isToday: true,
  },
  {
    ini: '현',
    color: '#0f766e',
    name: '현대건설',
    code: '000720',
    badge: 1,
    badgeColor: '#2563eb',
    relativeTime: '2일 전',
    summaryLine: '기업·실적 외 1건',
    items: [
      {
        dotColor: '#2563eb',
        headline: '수주 공시·실적 개선 기대',
        chg: '+2.14%',
        desc: '신규 수주 공시와 비용 안정화 전망이 맞물리며 투자 심리가 개선됐습니다.',
        tags: [{ label: '기업·실적', variant: 'solid', tone: 'neutral' }],
      },
    ],
    date: '2026.03.14',
    isToday: false,
  },
];
